---
all:
  children:
    ipa_servers:
      hosts:
        ipa01.sentinel.example.test:
          ansible_host: 192.0.2.10

    sentinel_servers:
      hosts:
        sentinel01.sentinel.example.test:
          ansible_host: 192.0.2.20

    sentinel_agents:
      hosts:
        agent01.sentinel.example.test:
          ansible_host: 192.0.2.30
        agent02.sentinel.example.test:
          ansible_host: 192.0.2.31

    ipaclients:
      children:
        sentinel_servers: {}
        sentinel_agents: {}
