---
ipaclient_domain: sentinel.example.test
ipaclient_realm: SENTINEL.EXAMPLE.TEST
ipaclient_servers:
  - ipa01.sentinel.example.test
ipaclient_mkhomedir: true
ipaclient_no_ntp: true
ipaadmin_principal: admin
